/**
 * Regression: template settings — upload valid .docx → metadata visible;
 * upload .exe → 415 toast; upload > 5 MB → size error toast;
 * download current template.
 */
import path from 'path';
import { fileURLToPath } from 'url';
import { test, expect } from '../fixtures/test';
import { SettingsTemplatePage } from '../pages/SettingsTemplatePage';
import { LoginPage } from '../pages/LoginPage';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const FIXTURES_DIR = path.resolve(__dirname, '../fixtures/files');
// Large generated fixtures written by global-setup to avoid source-tree writes in CI
const FIXTURES_TMP = process.env['E2E_FIXTURES_TMP'] ?? FIXTURES_DIR;

const ADMIN = {
  email: process.env['E2E_USERNAME'] ?? 'admin@example.com',
  password: process.env['E2E_PASSWORD'] ?? 'Secret1!',
};

async function login(page: import('@playwright/test').Page) {
  const loginPage = new LoginPage(page);
  await loginPage.goto();
  await loginPage.login(ADMIN.email, ADMIN.password);
  await expect(page).toHaveURL('/', { timeout: 10000 });
}

test('upload valid .docx → metadata filename visible', async ({ page }) => {
  await login(page);

  const templatePage = new SettingsTemplatePage(page);
  await templatePage.goto();

  await templatePage.uploadFile(path.join(FIXTURES_DIR, 'sample-template.docx'));

  await expect(page.locator('[data-sonner-toast]').first()).toBeVisible({ timeout: 10000 });
  await expect(templatePage.metadataFilename()).toBeVisible({ timeout: 10000 });
});

test('upload .exe → 415 or invalid type toast', async ({ page }) => {
  await login(page);

  const templatePage = new SettingsTemplatePage(page);
  await templatePage.goto();

  // The file input only accepts .docx, so the client-side check should reject it
  // We directly set the file on the input to bypass browser accept attribute
  const exePath = path.join(FIXTURES_DIR, 'evil.exe');

  // Set input files directly (bypasses accept attribute restriction)
  const input = page.getByTestId('template-file-input');
  await input.setInputFiles(exePath);

  // Toast should appear immediately (client-side validation)
  await expect(page.locator('[data-sonner-toast]').first()).toBeVisible({ timeout: 5000 });
  // Upload button should remain disabled (no valid file selected)
  await expect(page.getByTestId('btn-upload-template')).toBeDisabled();
});

test('upload oversized file → size error toast', async ({ page }) => {
  // File is generated by global-setup.ts into $E2E_FIXTURES_TMP (temp dir)
  // so the source tree remains read-only in CI
  const oversizedPath = path.join(FIXTURES_TMP, 'oversized-template.docx');

  await login(page);

  const templatePage = new SettingsTemplatePage(page);
  await templatePage.goto();

  const input = page.getByTestId('template-file-input');
  await input.setInputFiles(oversizedPath);

  // Client-side size validation should reject it and show a toast
  await expect(page.locator('[data-sonner-toast]').first()).toBeVisible({ timeout: 5000 });
  await expect(page.getByTestId('btn-upload-template')).toBeDisabled();
});

test('download current template button is visible after upload', async ({ page }) => {
  await login(page);

  const templatePage = new SettingsTemplatePage(page);
  await templatePage.goto();

  // Upload first
  await templatePage.uploadFile(path.join(FIXTURES_DIR, 'sample-template.docx'));
  await expect(page.locator('[data-sonner-toast]').first()).toBeVisible({ timeout: 10000 });

  // Reload to see updated metadata
  await page.reload();
  await templatePage.goto();

  await expect(templatePage.downloadCurrentButton()).toBeVisible({ timeout: 5000 });
});
